export enum BaseActions {
  IMAGE_UPLOADED = 'IMAGE_UPLOADED',
  SET_COLOR = 'SET_COLOR',
  GET_COLOR = 'GET_COLOR',
  SET_LUPA_SCALE = 'SET_LUPA_SCALE',
  INCREASE_LUPA_SCALE = 'INCREASE_LUPA_SCALE',
  DECREASE_LUPA_SCALE = 'DECREASE_LUPA_SCALE',
}
